### ISSUE TITLE
Add labels automatically based on activity in 'Github Projects'

### ISSUE THREAD

**Issue by iteles** [dwyl/dwylbot#181]
The main issue we've had with using github Projects (which in itself is undoubtedly useful to keep things organised and available for an at-a-glance view of where things are at) is the duplication of work in terms of having to add a label _and_ move an issue from one column to the other.

The fact that you have to 'touch' the same issue twice for the same purpose means that  in practice either one or the other isn't done 50% of the time (on average, for some people, this is closer to 100% of the time).

## Tasks
+ [ ] Determine which label should be attached to the issue in which column based on https://github.com/dwyl/contributing/issues/110
+ [ ] Review dwylbot to ensure that all _current_ rules are part of the existing documentation
+ [ ] Review all open pull requests (close any that are no longer relevant)
+ [ ] Write out the technical tasks required to add a label to an issue when it is moved to a new column
+ [ ] Implement two labels as an MVP
